export OS__USER_DOMAIN_NAME=Default
export OS__IMAGE_API_VERSION=2
export OS__PROJECT_NAME=demo
export OS__IDENTITY_API_VERSION=3
export OS__PASSWORD=senhaDaVMdoMato
export OS__AUTH_TYPE=password
export OS__AUTH_URL=http://controller:5000/v3
export OS__USERNAME=demo
export OS__PROJECT_DOMAIN_NAME=Default
echo "export OS_USER_DOMAIN_NAME=Default" >> /etc/bash.bashrc
echo "export OS_IMAGE_API_VERSION=2" >> /etc/bash.bashrc
echo "export OS_PROJECT_NAME=demo" >> /etc/bash.bashrc
echo "export OS_IDENTITY_API_VERSION=3" >> /etc/bash.bashrc
echo "export OS_PASSWORD=senhaDaVMdoMato" >> /etc/bash.bashrc
echo "export OS_AUTH_TYPE=password" >> /etc/bash.bashrc
echo "export OS_AUTH_URL=http://controller:5000/v3" >> /etc/bash.bashrc
echo "export OS_USERNAME=demo" >> /etc/bash.bashrc
echo "export OS_PROJECT_DOMAIN_NAME=Default" >> /etc/bash.bashrc
